// <auto-generated />
using System;
using AMIProjectAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMIProjectAPI.Migrations
{
    [DbContext(typeof(AmiprojectContext))]
    [Migration("20251107111814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMIProjectAPI.Models.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MeterID");

                    b.Property<DateOnly>("MonthStartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MonthlyConsumptionkWh")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("SlabRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("BillId")
                        .HasName("PK__Bill__11F2FC4A1C500DE9");

                    b.HasIndex("MeterId");

                    b.ToTable("Bill", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Consumer", b =>
                {
                    b.Property<int>("ConsumerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("admin");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TariffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ConsumerId")
                        .HasName("PK__Consumer__63BBE99A5C9FCA66");

                    b.HasIndex("TariffId");

                    b.ToTable("Consumer", null, t =>
                        {
                            t.HasTrigger("trg_Update_ConsumerTimestamp");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.ConsumerLogin", b =>
                {
                    b.Property<int>("ConsumerLoginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConsumerLoginID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsumerLoginId"));

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConsumerLoginId")
                        .HasName("PK__Consumer__E6D708D7B043FE72");

                    b.HasIndex(new[] { "Username" }, "UQ__Consumer__536C85E4C807DF73")
                        .IsUnique();

                    b.HasIndex(new[] { "ConsumerId" }, "UQ__Consumer__63BBE99B92114195")
                        .IsUnique();

                    b.ToTable("ConsumerLogin", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.DailyConsumption", b =>
                {
                    b.Property<DateOnly>("ConsumptionDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ConsumptionkWh")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MeterId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MeterID");

                    b.HasIndex("MeterId");

                    b.ToTable("DailyConsumption", null, t =>
                        {
                            t.HasTrigger("trg_UpdateMonthlyConsumption");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Meter", b =>
                {
                    b.Property<string>("MeterSerialNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int")
                        .HasColumnName("ConsumerID");

                    b.Property<string>("Firmware")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Iccid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ICCID");

                    b.Property<string>("Imsi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IMSI");

                    b.Property<DateTime>("InstallDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrgUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("MeterSerialNo")
                        .HasName("PK__Meter__5C498B0F46828ACB");

                    b.HasIndex("ConsumerId");

                    b.HasIndex("OrgUnitId");

                    b.ToTable("Meter", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.MonthlyConsumption", b =>
                {
                    b.Property<string>("MeterId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MeterID");

                    b.Property<DateOnly>("MonthStartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("ConsumptionkWh")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MeterId", "MonthStartDate");

                    b.ToTable("MonthlyConsumption", null, t =>
                        {
                            t.HasTrigger("trg_AutoGenerateBill");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.OrgUnit", b =>
                {
                    b.Property<int>("OrgUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrgUnitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgUnitId"));

                    b.Property<string>("Dtr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DTR");

                    b.Property<string>("Feeder")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Substation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Zone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrgUnitId")
                        .HasName("PK__OrgUnit__4A793B8EFD7ED6C3");

                    b.ToTable("OrgUnit", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Tariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("TariffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("TariffId")
                        .HasName("PK__Tariff__EBAF9D93007DC959");

                    b.ToTable("Tariff", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.TariffSlab", b =>
                {
                    b.Property<int>("SlabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlabId"));

                    b.Property<decimal>("FromKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<decimal>("RatePerKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("TariffId")
                        .HasColumnType("int")
                        .HasColumnName("TariffID");

                    b.Property<decimal>("ToKwh")
                        .HasColumnType("decimal(18, 6)");

                    b.HasKey("SlabId")
                        .HasName("PK__TariffSl__D61699213DA804C9");

                    b.HasIndex("TariffId");

                    b.ToTable("TariffSlab", (string)null);
                });

            modelBuilder.Entity("AMIProjectAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC457CD7F8");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E441FF4D7C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TodRule", b =>
                {
                    b.Property<int>("TodRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TodRuleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Multiplier")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeakType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TodRuleId");

                    b.ToTable("TodRules");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Bill", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Meter", "Meter")
                        .WithMany("Bills")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK__Bill__MeterID__08B54D69");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Consumer", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Tariff", "Tariff")
                        .WithMany("Consumers")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK__Consumer__Tariff__76969D2E");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.ConsumerLogin", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Consumer", "Consumer")
                        .WithOne("ConsumerLogin")
                        .HasForeignKey("AMIProjectAPI.Models.ConsumerLogin", "ConsumerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ConsumerL__Consu__114A936A");

                    b.Navigation("Consumer");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.DailyConsumption", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK__DailyCons__Meter__02FC7413");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Meter", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Consumer", "Consumer")
                        .WithMany("Meters")
                        .HasForeignKey("ConsumerId")
                        .IsRequired()
                        .HasConstraintName("FK__Meter__ConsumerI__7D439ABD");

                    b.HasOne("AMIProjectAPI.Models.OrgUnit", "OrgUnit")
                        .WithMany("Meters")
                        .HasForeignKey("OrgUnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Meter__OrgUnitId__7F2BE32F");

                    b.Navigation("Consumer");

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.MonthlyConsumption", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Meter", "Meter")
                        .WithMany("MonthlyConsumptions")
                        .HasForeignKey("MeterId")
                        .IsRequired()
                        .HasConstraintName("FK__MonthlyCo__Meter__05D8E0BE");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.TariffSlab", b =>
                {
                    b.HasOne("AMIProjectAPI.Models.Tariff", "Tariff")
                        .WithMany("TariffSlabs")
                        .HasForeignKey("TariffId")
                        .IsRequired()
                        .HasConstraintName("FK__TariffSla__Tarif__72C60C4A");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Consumer", b =>
                {
                    b.Navigation("ConsumerLogin");

                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Meter", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("MonthlyConsumptions");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.OrgUnit", b =>
                {
                    b.Navigation("Meters");
                });

            modelBuilder.Entity("AMIProjectAPI.Models.Tariff", b =>
                {
                    b.Navigation("Consumers");

                    b.Navigation("TariffSlabs");
                });
#pragma warning restore 612, 618
        }
    }
}
